# Generated by Django 4.2.28 on 2026-02-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='地域名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='中心緯度')),
                ('center_lon', models.FloatField(blank=True, null=True, verbose_name='中心経度')),
                ('footprint_wkt', models.TextField(blank=True, help_text='e.g. POLYGON((139.10 34.94, 139.13 34.94, ...))', verbose_name='範囲（WKT POLYGON）')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '対象地域',
                'verbose_name_plural': '対象地域',
            },
        ),
    ]
