# Generated by Django 4.2.28 on 2026-02-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_date', models.DateField(verbose_name='シーン日付')),
                ('product_id', models.CharField(blank=True, max_length=255, verbose_name='Sentinel product ID')),
                ('status', models.CharField(choices=[('pending', '取得待ち'), ('downloading', '取得中'), ('downloaded', '取得済み'), ('failed', '取得失敗')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='MEDIA_ROOT 相対または絶対パス', max_length=512, verbose_name='ダウンロード済みファイルパス')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='メタデータ')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_scenes', to='areas.area')),
            ],
            options={
                'verbose_name': '衛星シーン',
                'verbose_name_plural': '衛星シーン',
                'ordering': ['-scene_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='satellitescene',
            constraint=models.UniqueConstraint(fields=('area', 'scene_date'), name='unique_area_scene_date'),
        ),
    ]
