# Generated by Django 4.2.28 on 2026-02-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待機'), ('running', '実行中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='pending', max_length=20)),
                ('params', models.JSONField(default=dict, verbose_name='パラメータ')),
                ('before_date_start', models.DateField(blank=True, null=True, verbose_name='Before 開始日')),
                ('before_date_end', models.DateField(blank=True, null=True, verbose_name='Before 終了日')),
                ('after_date_start', models.DateField(blank=True, null=True, verbose_name='After 開始日')),
                ('after_date_end', models.DateField(blank=True, null=True, verbose_name='After 終了日')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_jobs', to='areas.area')),
            ],
            options={
                'verbose_name': '検出ジョブ',
                'verbose_name_plural': '検出ジョブ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deforestation_geojson', models.JSONField(blank=True, null=True, verbose_name='伐採エリア GeoJSON')),
                ('metrics', models.JSONField(default=dict, verbose_name='メトリクス')),
                ('violations', models.JSONField(default=list, verbose_name='違反疑い')),
                ('accuracy', models.JSONField(blank=True, default=dict, verbose_name='精度指標')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='detections.detectionjob')),
            ],
            options={
                'verbose_name': '検出結果',
                'verbose_name_plural': '検出結果',
            },
        ),
    ]
